include:
  - path: baseConfig.yml

targets:
  ${PROJECT_NAME}:
    type: application
    platform: iOS
    sources:
      - path: App
        createIntermediateGroups: NO
    postBuildScripts:
      - name: SwiftLint
        path: Scripts/run-swiftlint.sh
        basedOnDependencyAnalysis: NO
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: AsyncBindingDemo
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: Resolver
      - package: AsyncBinding
